
#TODO: English keywords
texts = {
    "English": {
        "greet": "Hello, world!",
        "K_panelID":"控制器地址",
        "K_IP":"IP地址",
        "K_loopID":"回路地址",
        "K_subnetMask":"子网掩码",
        "K_pointID":"点地址",
        "K_gateway":"默认网关",
        "K_channelID":"通道地址",
        "K_topologyType":"拓扑类型",
        "K_groundDetection":"接地检测",
        "K_pointsChanels":"点&通道_1_",
        "K_panel":"控制器",
        "K_ID":"名称",
        "K_loop":"回路",
        "K_systemID":"系统地址",
        "K_type":"类型",
        "UI_CBMoreInformation":"More Informaton:",
        "UI_HPConfig_0":"FS 30i Port Config",
        "UI_CPConfig_1":"1. Select the FS30i configuration file you want to load",
        "UI_CPConfig_2":"2. Select the hardware interfaces that need to be mapped",
        "UI_CPConfig_3":"3. Configure hardware interfaces",
        "UI_CPConfig_4":"4. Select the panel you want to map to the hardware interface",
        "UI_HMapping_0":"FS 30i Object Mapping",
        "UI_COMapping_1":"1. Select the hardware interface you want to map",
        "UI_COMapping_2":"2. Select the types of objects you want to map",
        "UI_COMapping_3":"3. Configure base address of Modbus for each type",
        "UI_COMapping_4":"4. Configure Modbus addresses manually",
        "UI_COMapping_5":"5. Export objects mapping CSV file",
        "UI_Tabload30Config":"Load FS30i Configuration File",
        "UI_TabloadProjectFile":"Load Project File",
        "UI_FUloadOldFile":"Load Old File",
        "UI_FUloadNewFile":"Load New File",
        "UI_WreducedTables":"Reduced Tables",
        "UI_WaddedTables":"Added Tables",
        "UI_MSshowComparedContent":"Show compared content",
        "UI_SBsheetForComparing":"Choose sheet for comparing (currently: controller, loop, point & channel)",
        "UI_WloadedFile":"Current Loaded File:",
        "UI_MSModbusHW":"Select Modbus Hardware Interfaces",
        "UI_TIIP":"IP:",
        "UI_TIPort":"Port:",
        "UI_WPanelSlave":"Select the panel mapping to the modbus slave",
        "UI_BTAddSlave":"Add Slave",
        "UI_BTSortSlave":"Sort Slaves",
        "UI_DBTExportConfig":"Export HW Interfaces Configuration File",
        "UI_MSObjectTypes":"Select the types of object you want to convert",
        "UI_NIModbusBaseAddr":"Modbus Base Address",
        "UI_WMappingResults":"Mapping Results",
        "UI_DBTExportCSV":"Export mapping CSV file",
        "UI_DBTExportProject":"Export Project"
        },
    "中文": {
        "greet": "你好，世界！",
        "K_panelID":"控制器地址",
        "K_IP":"IP地址",
        "K_loopID":"回路地址",
        "K_subnetMask":"子网掩码",
        "K_pointID":"点地址",
        "K_gateway":"默认网关",
        "K_channelID":"通道地址",
        "K_topologyType":"拓扑类型",
        "K_groundDetection":"接地检测",
        "K_pointsChanels":"点&通道_1_",
        "K_panel":"控制器",
        "K_ID":"名称",
        "K_loop":"回路",
        "K_systemID":"系统地址",
        "K_type":"类型",
        "UI_CBMoreInformation":"更多信息:",
        "UI_HPConfig_0":"FS30i 端口配置",
        "UI_CPConfig_1":"1.选择要加载的FS30i配置文件",
        "UI_CPConfig_2":"2. 选择需要映射的硬件接口",
        "UI_CPConfig_3":"3. 配置硬件接口",
        "UI_CPConfig_4":"4. 选择要映射到硬件接口的面板",
        "UI_HMapping_0":"FS30i 对象映射",
        "UI_COMapping_1":"1. 选择需要映射的硬件接口",
        "UI_COMapping_2":"2. 选择要映射的对象类型",
        "UI_COMapping_3":"3. 配置每种类型的Modbus基址",
        "UI_COMapping_4":"4. 手动配置Modbus地址",
        "UI_COMapping_5":"5. 导出对象映射CSV文件",
        "UI_Tabload30Config":"载入FS30i配置文件",
        "UI_TabloadProjectFile":"载入工程文件",
        "UI_FUloadOldFile":"载入老文件",
        "UI_FUloadNewFile":"载入新文件",
        "UI_WreducedTables":"减少的表",
        "UI_WaddedTables":"新增的表",
        "UI_MSshowComparedContent":"比较显示的内容",
        "UI_SBsheetForComparing":"选择要比较的表(当前：控制器,回路,点&通道)",
        "UI_WloadedFile":"加载的文件：",
        "UI_MSModbusHW":"选择Modbus的硬件接口",
        "UI_TIIP":"IP地址:",
        "UI_TIPort":"IP端口号:",
        "UI_WPanelSlave":"增加Modbus Slave端并选择控制器",
        "UI_BTAddSlave":"加Slave",
        "UI_BTSortSlave":"排序Slaves",
        "UI_DBTExportConfig":"导出硬件接口配置文件",
        "UI_MSObjectTypes":"选择要转换的对象类型",
        "UI_NIModbusBaseAddr":"Modbus基地址",
        "UI_WMappingResults":"映射结果",
        "UI_DBTExportCSV":"导出映射CSV文件",
        "UI_DBTExportProject":"导出工程"
        }
}
